### ISSUE TITLE
Fully random generator

### ISSUE THREAD

**Issue by ngokevin** [mattconsto/fantasy-names#5]
Have a way to get a random name from any of the generators in aggregate with no arguments:

`require('fantasy-names')()`

**Comment by ngokevin** [comment]
And a random from a generator category:

`require('fantasy-names')('places')`

**Comment by mattconsto** [comment]
I have made a few improvements including allowing no arguments. This changes the API, so the major version has been bumped. Now an array of results is returned instead of one string, use `.join` for the old behaviour. Thoughts? I'll push to NPM later.

**Comment by ngokevin** [comment]
Cool! It should be good. I'll give it a shot once it's on npm.
